version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - /home/${LOGIN}/data/WebsiteFiles:/www/data/   
    networks:
     - docker-network 
    restart: always
    depends_on:
     - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - /home/${LOGIN}/data/WebsiteFiles:/var/www/html/
    environment:
      DATABASE_NAME:      ${DATABASE_NAME}
      DATABASE_USER:      ${DATABASE_USER}
      DATABASE_PASSWORD:  ${DATABASE_PASSWORD}
      WP_URL:            ${WP_URL}
      WP_TITLE:          ${WP_TITLE}
      WP_ADMIN_LOGIN:    ${WP_ADMIN_LOGIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL:    ${WP_ADMIN_EMAIL}
      WP_USER_LOGIN:     ${WP_USER_LOGIN}
      WP_USER_PASSWORD:  ${WP_USER_PASSWORD}
      WP_USER_EMAIL:     ${WP_USER_EMAIL}
    networks:
     - docker-network
    restart: always
    depends_on:
     - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - /home/${LOGIN}/data/DataBase:/var/lib/mysql/
    environment:
      DATABASE_NAME:     ${DATABASE_NAME}
      DATABASE_USER:     ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
     - docker-network
    restart: always

networks:
  docker-network:
