version: '3'

services:

  nginx:
    image: nximg
    ports:
      - 443:443
    volumes:
      - /home/kkaczoro/data/WordPress:/www/data/

    # The hostname of the service (will be the same as the service name!)
    #hostname: nginx
    
    # Where the service exists (path) so you can build it
    # build:
    #   context: ./requirements/nginx
    #   dockerfile: Dockerfile
      
    # Restart to always keep the service restarting in case of any unexpected errors causing it to go down
    # restart: always
    
    # This line explains itself!!!
    # depends_on:
    #   - wordpress
      
    # The networks that the container will connect and communicate with the other containers
    # networks:
    #   - web